services:
  snippet-execution-service:
    build:
      context: .
      args:
        GPR_USER: ${GPR_USER}
        GPR_KEY: ${GPR_KEY}
    environment:
      SPRING_PROFILES_ACTIVE: prod

      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: ${EXECUTION_SERVICE_NEW_RELIC_APP_NAME}
    ports:
      - "8085:8080"
    networks:
      - snippetnet
networks:
  snippetnet:
    name: snippetnet
    driver: bridge