name: Build and Push Execution Service

on:
  push:
    branches: [ main, dev ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Determine tag
        id: vars
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "tag=latest" >> $GITHUB_ENV
          else
            echo "tag=dev" >> $GITHUB_ENV
          fi

      - name: Build and Push to GHCR
        uses: ingsisteam3-2025/snippet-searcher-actions-service/.github/actions/build-and-push@main
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          token: ${{ secrets.GHCR_TOKEN }}
          image: ghcr.io/ingsisteam3-2025/${{ github.event.repository.name }}:${{ env.tag }}

      - name: Trigger Infra Deployment
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        run: |
          branch=${GITHUB_REF_NAME}
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHCR_TOKEN }}" \
            https://api.github.com/repos/IngSisTeam3-2025/snippet-searcher-infra-service/dispatches \
            -d "{
              \"event_type\": \"deploy_from_service\",
              \"client_payload\": {
                \"branch\": \"$branch\",
                \"service\": \"execution-service\"
              }
            }"