name: CD

#on:
#  workflow_run:
#    workflows: ["CI"]
#    types: [completed]

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the exact commit that CI built
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Determine tag
        id: vars
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "tag=latest" >> $GITHUB_ENV
          else
            echo "tag=dev" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image
        uses: ingsisteam3-2025/snippet-searcher-actions-service/.github/actions/build-and-push@main
        with:
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
          image: ghcr.io/ingsisteam3-2025/snippet-searcher-execution-service:${{ env.tag }}
          gpr_user: ${{ secrets.GPR_USER }}
          gpr_key: ${{ secrets.GPR_KEY }}

      - name: Trigger Infra Deployment
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        run: |
          branch=${GITHUB_REF_NAME}
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHCR_TOKEN }}" \
            https://api.github.com/repos/IngSisTeam3-2025/snippet-searcher-infra-service/dispatches \
            -d "{
              \"event_type\": \"deploy_from_service\",
              \"client_payload\": {
                \"branch\": \"$branch\",
                \"service\": \"execution-service\"
              }
            }"
