name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  build-and-push:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      (github.event.workflow_run.head_branch == 'main' || 
       github.event.workflow_run.head_branch == 'dev')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout exact commit from CI
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          clean: true

      - name: Set tag
        run: |
          if [ "${{ github.event.workflow_run.head_branch }}" = "main" ]; then
            echo "tag=latest" >> $GITHUB_ENV
          else
            echo "tag=dev" >> $GITHUB_ENV
          fi

      - name: Print SHAs
        run: |
          echo "head_sha: ${{ github.event.workflow_run.head_sha }}"
          echo "repo HEAD: $(git rev-parse HEAD)"


      - name: Build and Push to GHCR
        uses: ingsisteam3-2025/snippet-searcher-actions-service/.github/actions/build-and-push@main
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          token: ${{ secrets.GHCR_TOKEN }}
          image: ghcr.io/ingsisteam3-2025/${{ github.event.repository.name }}:${{ env.tag }}
          gpr_user: ${{ github.actor }}
          gpr_key: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Infra Deployment
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHCR_TOKEN }}" \
            https://api.github.com/repos/IngSisTeam3-2025/snippet-searcher-infra-service/dispatches \
            -d "{
              \"event_type\": \"deploy_from_service\",
              \"client_payload\": {
                \"branch\": \"${{ github.event.workflow_run.head_branch }}\",
                \"service\": \"execution-service\"
              }
            }"